//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Samples/LDtk to Unity/3.3.3/Sample/Samples/Typical_2D_platformer_example.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Typical_2D_platformer_example
{
    /// <summary>
    /// LDtk Enum for Typical_2D_platformer_example
    /// </summary>
    public enum Item
    {
        Knife,
        Healing_Plant,
        Meat,
        Boots,
        Water,
        Gem
    }
}